<?php
/**
 * IncomeMonthlyDataResource
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPIDataIntelligence\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * finAPI Data Intelligence RESTful Services
 *
 * The following pages give you some general information on how to use the API.  The actual API services documentation then follows further below. You can use the menu to jump between API sections.   This page has a built-in HTTP(S) client, so you can test the services directly from within this page, by filling in the request parameters and/or body in the respective services, and then hitting the TRY button. Note that you need to be authorized to make a successful API call. To authorize, refer to the 'Authorization' section of the API, or just use the OAUTH button that can be found near the TRY button.   You should also check out the Developer Portal for more information. If you need any help with the API, contact support@finapi.io   <sub>Application-Version: 1.582.0</sub>
 *
 * The version of the OpenAPI document: 2022.38.1
 * Contact: kontakt@finapi.io
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.2.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPIDataIntelligence\Client\Model;

use \ArrayAccess;
use \OpenAPIDataIntelligence\Client\ObjectSerializer;

/**
 * IncomeMonthlyDataResource Class Doc Comment
 *
 * @category Class
 * @description Income data (including salary and other income sources) organized by months). Here we take into consideration the data from both complete and incomplete motnhs inside the report period under review.
 * @package  OpenAPIDataIntelligence\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class IncomeMonthlyDataResource implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'IncomeMonthlyDataResource';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'total_monthly_amounts' => '\OpenAPIDataIntelligence\Client\Model\IncomeTotalMonthlyAmountsResource[]',
        'min_total_monthly_amount' => 'float',
        'max_total_monthly_amount' => 'float',
        'average_total_monthly_amount' => 'float',
        'median_total_monthly_amount' => 'float'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'total_monthly_amounts' => null,
        'min_total_monthly_amount' => null,
        'max_total_monthly_amount' => null,
        'average_total_monthly_amount' => null,
        'median_total_monthly_amount' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'total_monthly_amounts' => false,
		'min_total_monthly_amount' => false,
		'max_total_monthly_amount' => false,
		'average_total_monthly_amount' => false,
		'median_total_monthly_amount' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'total_monthly_amounts' => 'totalMonthlyAmounts',
        'min_total_monthly_amount' => 'minTotalMonthlyAmount',
        'max_total_monthly_amount' => 'maxTotalMonthlyAmount',
        'average_total_monthly_amount' => 'averageTotalMonthlyAmount',
        'median_total_monthly_amount' => 'medianTotalMonthlyAmount'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'total_monthly_amounts' => 'setTotalMonthlyAmounts',
        'min_total_monthly_amount' => 'setMinTotalMonthlyAmount',
        'max_total_monthly_amount' => 'setMaxTotalMonthlyAmount',
        'average_total_monthly_amount' => 'setAverageTotalMonthlyAmount',
        'median_total_monthly_amount' => 'setMedianTotalMonthlyAmount'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'total_monthly_amounts' => 'getTotalMonthlyAmounts',
        'min_total_monthly_amount' => 'getMinTotalMonthlyAmount',
        'max_total_monthly_amount' => 'getMaxTotalMonthlyAmount',
        'average_total_monthly_amount' => 'getAverageTotalMonthlyAmount',
        'median_total_monthly_amount' => 'getMedianTotalMonthlyAmount'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('total_monthly_amounts', $data ?? [], null);
        $this->setIfExists('min_total_monthly_amount', $data ?? [], null);
        $this->setIfExists('max_total_monthly_amount', $data ?? [], null);
        $this->setIfExists('average_total_monthly_amount', $data ?? [], null);
        $this->setIfExists('median_total_monthly_amount', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['total_monthly_amounts'] === null) {
            $invalidProperties[] = "'total_monthly_amounts' can't be null";
        }
        if ($this->container['min_total_monthly_amount'] === null) {
            $invalidProperties[] = "'min_total_monthly_amount' can't be null";
        }
        if ($this->container['max_total_monthly_amount'] === null) {
            $invalidProperties[] = "'max_total_monthly_amount' can't be null";
        }
        if ($this->container['average_total_monthly_amount'] === null) {
            $invalidProperties[] = "'average_total_monthly_amount' can't be null";
        }
        if ($this->container['median_total_monthly_amount'] === null) {
            $invalidProperties[] = "'median_total_monthly_amount' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets total_monthly_amounts
     *
     * @return \OpenAPIDataIntelligence\Client\Model\IncomeTotalMonthlyAmountsResource[]
     */
    public function getTotalMonthlyAmounts()
    {
        return $this->container['total_monthly_amounts'];
    }

    /**
     * Sets total_monthly_amounts
     *
     * @param \OpenAPIDataIntelligence\Client\Model\IncomeTotalMonthlyAmountsResource[] $total_monthly_amounts total_monthly_amounts
     *
     * @return self
     */
    public function setTotalMonthlyAmounts($total_monthly_amounts)
    {

        if (is_null($total_monthly_amounts)) {
            throw new \InvalidArgumentException('non-nullable total_monthly_amounts cannot be null');
        }

        $this->container['total_monthly_amounts'] = $total_monthly_amounts;

        return $this;
    }

    /**
     * Gets min_total_monthly_amount
     *
     * @return float
     */
    public function getMinTotalMonthlyAmount()
    {
        return $this->container['min_total_monthly_amount'];
    }

    /**
     * Sets min_total_monthly_amount
     *
     * @param float $min_total_monthly_amount The lowest amount of total monthly income (including salary and other income sources) within the report period under review.
     *
     * @return self
     */
    public function setMinTotalMonthlyAmount($min_total_monthly_amount)
    {

        if (is_null($min_total_monthly_amount)) {
            throw new \InvalidArgumentException('non-nullable min_total_monthly_amount cannot be null');
        }

        $this->container['min_total_monthly_amount'] = $min_total_monthly_amount;

        return $this;
    }

    /**
     * Gets max_total_monthly_amount
     *
     * @return float
     */
    public function getMaxTotalMonthlyAmount()
    {
        return $this->container['max_total_monthly_amount'];
    }

    /**
     * Sets max_total_monthly_amount
     *
     * @param float $max_total_monthly_amount The highest amount of total monthly income (including salary and other income sources) within the report period under review.
     *
     * @return self
     */
    public function setMaxTotalMonthlyAmount($max_total_monthly_amount)
    {

        if (is_null($max_total_monthly_amount)) {
            throw new \InvalidArgumentException('non-nullable max_total_monthly_amount cannot be null');
        }

        $this->container['max_total_monthly_amount'] = $max_total_monthly_amount;

        return $this;
    }

    /**
     * Gets average_total_monthly_amount
     *
     * @return float
     */
    public function getAverageTotalMonthlyAmount()
    {
        return $this->container['average_total_monthly_amount'];
    }

    /**
     * Sets average_total_monthly_amount
     *
     * @param float $average_total_monthly_amount Average amount of total monthly income (including salary and other income sources) within the report period under review.
     *
     * @return self
     */
    public function setAverageTotalMonthlyAmount($average_total_monthly_amount)
    {

        if (is_null($average_total_monthly_amount)) {
            throw new \InvalidArgumentException('non-nullable average_total_monthly_amount cannot be null');
        }

        $this->container['average_total_monthly_amount'] = $average_total_monthly_amount;

        return $this;
    }

    /**
     * Gets median_total_monthly_amount
     *
     * @return float
     */
    public function getMedianTotalMonthlyAmount()
    {
        return $this->container['median_total_monthly_amount'];
    }

    /**
     * Sets median_total_monthly_amount
     *
     * @param float $median_total_monthly_amount Median amount of total monthly income (including salary and other income sources) within the report period under review.
     *
     * @return self
     */
    public function setMedianTotalMonthlyAmount($median_total_monthly_amount)
    {

        if (is_null($median_total_monthly_amount)) {
            throw new \InvalidArgumentException('non-nullable median_total_monthly_amount cannot be null');
        }

        $this->container['median_total_monthly_amount'] = $median_total_monthly_amount;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


