<?php
/**
 * SchufaCreditCheckReportResource
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPIDataIntelligence\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * finAPI Data Intelligence RESTful Services
 *
 * The following pages give you some general information on how to use the API.  The actual API services documentation then follows further below. You can use the menu to jump between API sections.   This page has a built-in HTTP(S) client, so you can test the services directly from within this page, by filling in the request parameters and/or body in the respective services, and then hitting the TRY button. Note that you need to be authorized to make a successful API call. To authorize, refer to the 'Authorization' section of the API, or just use the OAUTH button that can be found near the TRY button.   You should also check out the Developer Portal for more information. If you need any help with the API, contact support@finapi.io   <sub>Application-Version: 1.582.0</sub>
 *
 * The version of the OpenAPI document: 2022.38.1
 * Contact: kontakt@finapi.io
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.2.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPIDataIntelligence\Client\Model;

use \ArrayAccess;
use \OpenAPIDataIntelligence\Client\ObjectSerializer;

/**
 * SchufaCreditCheckReportResource Class Doc Comment
 *
 * @category Class
 * @description report format
 * @package  OpenAPIDataIntelligence\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class SchufaCreditCheckReportResource implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'SchufaCreditCheckReportResource';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'id' => 'string',
        'creation_date' => 'string',
        'case_id' => 'string',
        'type' => 'string',
        'count_contracts' => 'int',
        'count_risks' => 'int',
        'count_contracts_filter' => 'string',
        'schufa_data' => '\OpenAPIDataIntelligence\Client\Model\SchufaCreditCheckReportResourceSchufaData'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'id' => null,
        'creation_date' => null,
        'case_id' => null,
        'type' => null,
        'count_contracts' => 'int32',
        'count_risks' => 'int32',
        'count_contracts_filter' => null,
        'schufa_data' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'id' => false,
		'creation_date' => false,
		'case_id' => false,
		'type' => false,
		'count_contracts' => false,
		'count_risks' => false,
		'count_contracts_filter' => false,
		'schufa_data' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'creation_date' => 'creationDate',
        'case_id' => 'caseId',
        'type' => 'type',
        'count_contracts' => 'countContracts',
        'count_risks' => 'countRisks',
        'count_contracts_filter' => 'countContractsFilter',
        'schufa_data' => 'schufaData'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'creation_date' => 'setCreationDate',
        'case_id' => 'setCaseId',
        'type' => 'setType',
        'count_contracts' => 'setCountContracts',
        'count_risks' => 'setCountRisks',
        'count_contracts_filter' => 'setCountContractsFilter',
        'schufa_data' => 'setSchufaData'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'creation_date' => 'getCreationDate',
        'case_id' => 'getCaseId',
        'type' => 'getType',
        'count_contracts' => 'getCountContracts',
        'count_risks' => 'getCountRisks',
        'count_contracts_filter' => 'getCountContractsFilter',
        'schufa_data' => 'getSchufaData'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const TYPE_SCHUFACREDITCHECK = 'SCHUFACREDITCHECK';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getTypeAllowableValues()
    {
        return [
            self::TYPE_SCHUFACREDITCHECK,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('creation_date', $data ?? [], null);
        $this->setIfExists('case_id', $data ?? [], null);
        $this->setIfExists('type', $data ?? [], null);
        $this->setIfExists('count_contracts', $data ?? [], null);
        $this->setIfExists('count_risks', $data ?? [], null);
        $this->setIfExists('count_contracts_filter', $data ?? [], null);
        $this->setIfExists('schufa_data', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['id'] === null) {
            $invalidProperties[] = "'id' can't be null";
        }
        if ($this->container['case_id'] === null) {
            $invalidProperties[] = "'case_id' can't be null";
        }
        if ($this->container['type'] === null) {
            $invalidProperties[] = "'type' can't be null";
        }
        $allowedValues = $this->getTypeAllowableValues();
        if (!is_null($this->container['type']) && !in_array($this->container['type'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'type', must be one of '%s'",
                $this->container['type'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['count_contracts'] === null) {
            $invalidProperties[] = "'count_contracts' can't be null";
        }
        if ($this->container['count_risks'] === null) {
            $invalidProperties[] = "'count_risks' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return string
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string $id UUID of the report
     *
     * @return self
     */
    public function setId($id)
    {

        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }

        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets creation_date
     *
     * @return string|null
     */
    public function getCreationDate()
    {
        return $this->container['creation_date'];
    }

    /**
     * Sets creation_date
     *
     * @param string|null $creation_date Timestamp of when the report was created, in the format '<code>YYYY-MM-DD HH:MM:SS</code>' (CET Europe / Berlin).
     *
     * @return self
     */
    public function setCreationDate($creation_date)
    {

        if (is_null($creation_date)) {
            throw new \InvalidArgumentException('non-nullable creation_date cannot be null');
        }

        $this->container['creation_date'] = $creation_date;

        return $this;
    }

    /**
     * Gets case_id
     *
     * @return string
     */
    public function getCaseId()
    {
        return $this->container['case_id'];
    }

    /**
     * Sets case_id
     *
     * @param string $case_id UUID of the case file
     *
     * @return self
     */
    public function setCaseId($case_id)
    {

        if (is_null($case_id)) {
            throw new \InvalidArgumentException('non-nullable case_id cannot be null');
        }

        $this->container['case_id'] = $case_id;

        return $this;
    }

    /**
     * Gets type
     *
     * @return string
     */
    public function getType()
    {
        return $this->container['type'];
    }

    /**
     * Sets type
     *
     * @param string $type Type of the report. <ul>   <li><code> SCHUFACREDITCHECK</code> - this report type returns the results of SCHUFA credit check and reported by SCHUFA contracts.</li> </ul>
     *
     * @return self
     */
    public function setType($type)
    {
        $allowedValues = $this->getTypeAllowableValues();
        if (!in_array($type, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'type', must be one of '%s'",
                    $type,
                    implode("', '", $allowedValues)
                )
            );
        }

        if (is_null($type)) {
            throw new \InvalidArgumentException('non-nullable type cannot be null');
        }

        $this->container['type'] = $type;

        return $this;
    }

    /**
     * Gets count_contracts
     *
     * @return int
     */
    public function getCountContracts()
    {
        return $this->container['count_contracts'];
    }

    /**
     * Sets count_contracts
     *
     * @param int $count_contracts The total count of active loan contracts, as reported by SCHUFA, depending on the filter.
     *
     * @return self
     */
    public function setCountContracts($count_contracts)
    {

        if (is_null($count_contracts)) {
            throw new \InvalidArgumentException('non-nullable count_contracts cannot be null');
        }

        $this->container['count_contracts'] = $count_contracts;

        return $this;
    }

    /**
     * Gets count_risks
     *
     * @return int
     */
    public function getCountRisks()
    {
        return $this->container['count_risks'];
    }

    /**
     * Sets count_risks
     *
     * @param int $count_risks The total count of credit risk features (Negativmerkmale), as reported by SCHUFA.
     *
     * @return self
     */
    public function setCountRisks($count_risks)
    {

        if (is_null($count_risks)) {
            throw new \InvalidArgumentException('non-nullable count_risks cannot be null');
        }

        $this->container['count_risks'] = $count_risks;

        return $this;
    }

    /**
     * Gets count_contracts_filter
     *
     * @return string|null
     */
    public function getCountContractsFilter()
    {
        return $this->container['count_contracts_filter'];
    }

    /**
     * Sets count_contracts_filter
     *
     * @param string|null $count_contracts_filter If a filter was set, this field contains the used characteristic codes.
     *
     * @return self
     */
    public function setCountContractsFilter($count_contracts_filter)
    {

        if (is_null($count_contracts_filter)) {
            throw new \InvalidArgumentException('non-nullable count_contracts_filter cannot be null');
        }

        $this->container['count_contracts_filter'] = $count_contracts_filter;

        return $this;
    }

    /**
     * Gets schufa_data
     *
     * @return \OpenAPIDataIntelligence\Client\Model\SchufaCreditCheckReportResourceSchufaData|null
     */
    public function getSchufaData()
    {
        return $this->container['schufa_data'];
    }

    /**
     * Sets schufa_data
     *
     * @param \OpenAPIDataIntelligence\Client\Model\SchufaCreditCheckReportResourceSchufaData|null $schufa_data schufa_data
     *
     * @return self
     */
    public function setSchufaData($schufa_data)
    {

        if (is_null($schufa_data)) {
            throw new \InvalidArgumentException('non-nullable schufa_data cannot be null');
        }

        $this->container['schufa_data'] = $schufa_data;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


